# Generated by Django 5.1.1 on 2024-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["last_bidding_at"]},
        ),
        migrations.AddField(
            model_name="listing",
            name="start_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
