# Generated by Django 5.1.1 on 2024-09-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_options_listing_start_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="start_price",
        ),
    ]
