# Generated by Django 5.1.1 on 2024-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_remove_listing_start_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bidding",
            new_name="Bid",
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["last_bid_at"]},
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="last_bidding_at",
            new_name="last_bid_at",
        ),
        migrations.AddField(
            model_name="listing",
            name="bid_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
