# Generated by Django 5.1.1 on 2024-09-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_bid_options_listing_start_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-last_bid_at"]},
        ),
    ]
