# Generated by Django 5.1.1 on 2024-09-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_bid_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(to="auctions.listing"),
        ),
    ]
