# Generated by Django 5.1.1 on 2024-09-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[("not", "Uncategory"), ("fam", "Family"), ("per", "Personal")],
                default="not",
                max_length=3,
            ),
        ),
    ]
