# Generated by Django 5.1.1 on 2024-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("uncategorized", "uncategorized"),
                    ("family", "family"),
                    ("personal", "personal"),
                ],
                default="uncategorized",
                max_length=50,
            ),
        ),
    ]
