# Generated by Django 5.1.1 on 2024-09-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_listing_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="created_at",
        ),
        migrations.AddField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
